// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Zuuse.Accounts.Client
{
    using Models;
    using System.Threading;
    using System.Threading.Tasks;

    /// <summary>
    /// Extension methods for EmailTemplates.
    /// </summary>
    public static partial class EmailTemplatesExtensions
    {
            /// <summary>
            /// The old API for access to email templates
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='request'>
            /// </param>
            public static object PostGetEmailTemplates(this IEmailTemplates operations, EmailTemplateRequest request)
            {
                return operations.PostGetEmailTemplatesAsync(request).GetAwaiter().GetResult();
            }

            /// <summary>
            /// The old API for access to email templates
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='request'>
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task<object> PostGetEmailTemplatesAsync(this IEmailTemplates operations, EmailTemplateRequest request, CancellationToken cancellationToken = default(CancellationToken))
            {
                using (var _result = await operations.PostGetEmailTemplatesWithHttpMessagesAsync(request, null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

            /// <summary>
            /// The old API for access to email templates
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='request'>
            /// </param>
            public static object PostCreateEmailTemplate(this IEmailTemplates operations, EmailTemplateCreateRequest request)
            {
                return operations.PostCreateEmailTemplateAsync(request).GetAwaiter().GetResult();
            }

            /// <summary>
            /// The old API for access to email templates
            /// </summary>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='request'>
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task<object> PostCreateEmailTemplateAsync(this IEmailTemplates operations, EmailTemplateCreateRequest request, CancellationToken cancellationToken = default(CancellationToken))
            {
                using (var _result = await operations.PostCreateEmailTemplateWithHttpMessagesAsync(request, null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

    }
}
