// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Zuuse.Accounts.Client
{
    using Models;
    using Newtonsoft.Json;

    /// <summary>
    /// </summary>
    public partial interface IZuuseAccountsApi : System.IDisposable
    {
        /// <summary>
        /// The base URI of the service.
        /// </summary>
        System.Uri BaseUri { get; set; }

        /// <summary>
        /// Gets or sets json serialization settings.
        /// </summary>
        JsonSerializerSettings SerializationSettings { get; }

        /// <summary>
        /// Gets or sets json deserialization settings.
        /// </summary>
        JsonSerializerSettings DeserializationSettings { get; }


        /// <summary>
        /// Gets the IAccount.
        /// </summary>
        IAccount Account { get; }

        /// <summary>
        /// Gets the IAccounts.
        /// </summary>
        IAccounts Accounts { get; }

        /// <summary>
        /// Gets the IClientProject.
        /// </summary>
        IClientProject ClientProject { get; }

        /// <summary>
        /// Gets the IEmailTemplates.
        /// </summary>
        IEmailTemplates EmailTemplates { get; }

        /// <summary>
        /// Gets the IExternalAccount.
        /// </summary>
        IExternalAccount ExternalAccount { get; }

        /// <summary>
        /// Gets the IZuuse.
        /// </summary>
        IZuuse Zuuse { get; }

    }
}
