// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

namespace Zuuse.Accounts.Client.Models
{
    /// <summary> The AccountRegistrationRequest. </summary>
    public partial class AccountRegistrationRequest
    {
        /// <summary> Initializes a new instance of AccountRegistrationRequest. </summary>
        public AccountRegistrationRequest()
        {
        }

        public string Username { get; set; }
        public string Password { get; set; }
        public int? ExpiryInDays { get; set; }
        public bool? MultiUse { get; set; }
        public string Name { get; set; }
        public string Phone { get; set; }
        public int? ClientId { get; set; }
        public int? ProjectId { get; set; }
    }
}
