// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

namespace Zuuse.Accounts.Client.Models
{
    /// <summary> The AccountLoginRequest. </summary>
    public partial class AccountLoginRequest
    {
        /// <summary> Initializes a new instance of AccountLoginRequest. </summary>
        public AccountLoginRequest()
        {
        }

        public string Username { get; set; }
        public string Password { get; set; }
    }
}
