// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

namespace Zuuse.Accounts.Client.Models
{
    /// <summary> The AccountDetailsByIdRequest. </summary>
    public partial class AccountDetailsByIdRequest
    {
        /// <summary> Initializes a new instance of AccountDetailsByIdRequest. </summary>
        public AccountDetailsByIdRequest()
        {
        }

        public int? ClientId { get; set; }
        public int? ProjectId { get; set; }
        public string AccountId { get; set; }
    }
}
