// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

namespace Zuuse.Accounts.Client.Models
{
    /// <summary> The AccountPasswordChangeRequest. </summary>
    public partial class AccountPasswordChangeRequest
    {
        /// <summary> Initializes a new instance of AccountPasswordChangeRequest. </summary>
        public AccountPasswordChangeRequest()
        {
        }

        public string OldPassword { get; set; }
        public string NewPassword { get; set; }
    }
}
