// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Zuuse.Accounts.Client.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class Applications
    {
        /// <summary>
        /// Initializes a new instance of the Applications class.
        /// </summary>
        public Applications()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the Applications class.
        /// </summary>
        public Applications(bool? core = default(bool?), bool? assets = default(bool?), bool? assessments = default(bool?), bool? finances = default(bool?), bool? lifecycleCore = default(bool?), bool? lifecycleSkyline = default(bool?), bool? lifecycleEqualiser = default(bool?))
        {
            Core = core;
            Assets = assets;
            Assessments = assessments;
            Finances = finances;
            LifecycleCore = lifecycleCore;
            LifecycleSkyline = lifecycleSkyline;
            LifecycleEqualiser = lifecycleEqualiser;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Core")]
        public bool? Core { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Assets")]
        public bool? Assets { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Assessments")]
        public bool? Assessments { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Finances")]
        public bool? Finances { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "LifecycleCore")]
        public bool? LifecycleCore { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "LifecycleSkyline")]
        public bool? LifecycleSkyline { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "LifecycleEqualiser")]
        public bool? LifecycleEqualiser { get; set; }

    }
}
