// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

namespace Zuuse.Accounts.Client.Models
{
    /// <summary> The ChangePasswordRequest. </summary>
    public partial class ChangePasswordRequest
    {
        /// <summary> Initializes a new instance of ChangePasswordRequest. </summary>
        public ChangePasswordRequest()
        {
        }

        public string Username { get; set; }
        public string OldPassword { get; set; }
        public string NewPassword { get; set; }
    }
}
