// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

namespace Zuuse.Accounts.Client.Models
{
    /// <summary> The ClientProjectRequest. </summary>
    public partial class ClientProjectRequest
    {
        /// <summary> Initializes a new instance of ClientProjectRequest. </summary>
        public ClientProjectRequest()
        {
        }

        public string ClientProjectName { get; set; }
        public string ClientShortName { get; set; }
        public int? ClientId { get; set; }
        public int? ProjectId { get; set; }
        public int? CADocTypeId { get; set; }
        public string EwsApiLocation { get; set; }
    }
}
