// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

namespace Zuuse.Accounts.Client.Models
{
    /// <summary> The ClientProjectIds. </summary>
    public partial class ClientProjectIds
    {
        /// <summary> Initializes a new instance of ClientProjectIds. </summary>
        public ClientProjectIds()
        {
        }

        public int? ClientId { get; set; }
        public int? ProjectId { get; set; }
    }
}
