// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

namespace Zuuse.Accounts.Client.Models
{
    /// <summary> The EmailTemplateRequest. </summary>
    public partial class EmailTemplateRequest
    {
        /// <summary> Initializes a new instance of EmailTemplateRequest. </summary>
        public EmailTemplateRequest()
        {
        }

        public int? ClientId { get; set; }
        public int? ProjectId { get; set; }
        public string TemplateName { get; set; }
    }
}
