// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

namespace Zuuse.Accounts.Client.Models
{
    /// <summary> The EmailTemplateCreateRequest. </summary>
    public partial class EmailTemplateCreateRequest
    {
        /// <summary> Initializes a new instance of EmailTemplateCreateRequest. </summary>
        public EmailTemplateCreateRequest()
        {
        }

        public int? ClientId { get; set; }
        public int? ProjectId { get; set; }
        public string Name { get; set; }
        public string Body { get; set; }
        public string Subject { get; set; }
        public string FromEmail { get; set; }
    }
}
