// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System;

namespace Zuuse.Accounts.Client.Models
{
    /// <summary> The ExternalAccountRegistrationRequest. </summary>
    public partial class ExternalAccountRegistrationRequest
    {
        /// <summary> Initializes a new instance of ExternalAccountRegistrationRequest. </summary>
        public ExternalAccountRegistrationRequest()
        {
        }

        public string Name { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public int? ExpiryInDays { get; set; }
        public bool? MultiUse { get; set; }
        public int? ClientId { get; set; }
        public int? ProjectId { get; set; }
        public Guid? FilterGuid { get; set; }
    }
}
