// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Zuuse.Accounts.Client.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class ExternalAccountDetailsByIdRequest
    {
        /// <summary>
        /// Initializes a new instance of the ExternalAccountDetailsByIdRequest
        /// class.
        /// </summary>
        public ExternalAccountDetailsByIdRequest()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the ExternalAccountDetailsByIdRequest
        /// class.
        /// </summary>
        public ExternalAccountDetailsByIdRequest(int? clientId = default(int?), int? projectId = default(int?), string externalAccountId = default(string))
        {
            ClientId = clientId;
            ProjectId = projectId;
            ExternalAccountId = externalAccountId;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ClientId")]
        public int? ClientId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ProjectId")]
        public int? ProjectId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ExternalAccountId")]
        public string ExternalAccountId { get; set; }

    }
}
