// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

namespace Zuuse.Accounts.Client.Models
{
    /// <summary> The ExternalAccountDetailsByIdRequest. </summary>
    public partial class ExternalAccountDetailsByIdRequest
    {
        /// <summary> Initializes a new instance of ExternalAccountDetailsByIdRequest. </summary>
        public ExternalAccountDetailsByIdRequest()
        {
        }

        public int? ClientId { get; set; }
        public int? ProjectId { get; set; }
        public string ExternalAccountId { get; set; }
    }
}
