// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Zuuse.Accounts.Client.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class LoginRequest
    {
        /// <summary>
        /// Initializes a new instance of the LoginRequest class.
        /// </summary>
        public LoginRequest()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the LoginRequest class.
        /// </summary>
        public LoginRequest(string identifyingKey = default(string), string password = default(string))
        {
            IdentifyingKey = identifyingKey;
            Password = password;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "IdentifyingKey")]
        public string IdentifyingKey { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Password")]
        public string Password { get; set; }

    }
}
