// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System;

namespace Zuuse.Accounts.Client.Models
{
    /// <summary> The LoginResponse. </summary>
    public partial class LoginResponse
    {
        /// <summary> Initializes a new instance of LoginResponse. </summary>
        internal LoginResponse()
        {
        }

        /// <summary> Initializes a new instance of LoginResponse. </summary>
        /// <param name="userId"> . </param>
        /// <param name="token"> . </param>
        /// <param name="clientProjectId"> . </param>
        /// <param name="clientShortName"> . </param>
        /// <param name="clientId"> . </param>
        /// <param name="projectId"> . </param>
        /// <param name="loginId"> . </param>
        /// <param name="name"> . </param>
        /// <param name="email"> . </param>
        /// <param name="phone"> . </param>
        /// <param name="externalAccountId"> . </param>
        /// <param name="accountId"> . </param>
        /// <param name="filterGuid"> . </param>
        /// <param name="ewsApiLocation"> . </param>
        internal LoginResponse(string userId, string token, string clientProjectId, string clientShortName, int? clientId, int? projectId, long? loginId, string name, string email, string phone, string externalAccountId, string accountId, Guid? filterGuid, string ewsApiLocation)
        {
            UserId = userId;
            Token = token;
            ClientProjectId = clientProjectId;
            ClientShortName = clientShortName;
            ClientId = clientId;
            ProjectId = projectId;
            LoginId = loginId;
            Name = name;
            Email = email;
            Phone = phone;
            ExternalAccountId = externalAccountId;
            AccountId = accountId;
            FilterGuid = filterGuid;
            EwsApiLocation = ewsApiLocation;
        }

        public string UserId { get; }
        public string Token { get; }
        public string ClientProjectId { get; }
        public string ClientShortName { get; }
        public int? ClientId { get; }
        public int? ProjectId { get; }
        public long? LoginId { get; }
        public string Name { get; }
        public string Email { get; }
        public string Phone { get; }
        public string ExternalAccountId { get; }
        public string AccountId { get; }
        public Guid? FilterGuid { get; }
        public string EwsApiLocation { get; }
    }
}
