// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

namespace Zuuse.Accounts.Client.Models
{
    /// <summary> The LoginRequest. </summary>
    public partial class LoginRequest
    {
        /// <summary> Initializes a new instance of LoginRequest. </summary>
        public LoginRequest()
        {
        }

        public string IdentifyingKey { get; set; }
        public string Password { get; set; }
        public string SSOToken { get; set; }
        public string RedirectUri { get; set; }
    }
}
