// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

namespace Zuuse.Accounts.Client.Models
{
    /// <summary> The PinLoginRequest. </summary>
    public partial class PinLoginRequest
    {
        /// <summary> Initializes a new instance of PinLoginRequest. </summary>
        public PinLoginRequest()
        {
        }

        public string Pin { get; set; }
    }
}
