// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

namespace Zuuse.Accounts.Client.Models
{
    /// <summary> The ResetPasswordResponse. </summary>
    internal partial class ResetPasswordResponse
    {
        /// <summary> Initializes a new instance of ResetPasswordResponse. </summary>
        internal ResetPasswordResponse()
        {
        }

        public string NewPassword { get; }
    }
}
