// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System.Collections.Generic;
using Azure.Core;

namespace Zuuse.Accounts.Client.Models
{
    /// <summary> The RoleCollection. </summary>
    public partial class RoleCollection
    {
        /// <summary> Initializes a new instance of RoleCollection. </summary>
        public RoleCollection()
        {
            BuiltInRoles = new ChangeTrackingList<RoleCollectionBuiltInRolesItem>();
            CustomRoles = new ChangeTrackingList<string>();
        }

        /// <summary> Initializes a new instance of RoleCollection. </summary>
        /// <param name="builtInRoles"> . </param>
        /// <param name="customRoles"> . </param>
        internal RoleCollection(IReadOnlyList<RoleCollectionBuiltInRolesItem> builtInRoles, IReadOnlyList<string> customRoles)
        {
            BuiltInRoles = builtInRoles;
            CustomRoles = customRoles;
        }

        public IReadOnlyList<RoleCollectionBuiltInRolesItem> BuiltInRoles { get; }
        public IReadOnlyList<string> CustomRoles { get; }
    }
}
