// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Zuuse.Accounts.Client.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class AccountRegistrationRequest
    {
        /// <summary>
        /// Initializes a new instance of the AccountRegistrationRequest class.
        /// </summary>
        public AccountRegistrationRequest()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the AccountRegistrationRequest class.
        /// </summary>
        public AccountRegistrationRequest(string username = default(string), string password = default(string), int? expiryInDays = default(int?), bool? multiUse = default(bool?), string name = default(string), string phone = default(string), int? clientId = default(int?), int? projectId = default(int?))
        {
            Username = username;
            Password = password;
            ExpiryInDays = expiryInDays;
            MultiUse = multiUse;
            Name = name;
            Phone = phone;
            ClientId = clientId;
            ProjectId = projectId;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Username")]
        public string Username { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Password")]
        public string Password { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ExpiryInDays")]
        public int? ExpiryInDays { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "MultiUse")]
        public bool? MultiUse { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Name")]
        public string Name { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Phone")]
        public string Phone { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ClientId")]
        public int? ClientId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ProjectId")]
        public int? ProjectId { get; set; }

    }
}
