// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Zuuse.Accounts.Client.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class AccountPasswordChangeRequest
    {
        /// <summary>
        /// Initializes a new instance of the AccountPasswordChangeRequest
        /// class.
        /// </summary>
        public AccountPasswordChangeRequest()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the AccountPasswordChangeRequest
        /// class.
        /// </summary>
        public AccountPasswordChangeRequest(string oldPassword = default(string), string newPassword = default(string))
        {
            OldPassword = oldPassword;
            NewPassword = newPassword;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "OldPassword")]
        public string OldPassword { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "NewPassword")]
        public string NewPassword { get; set; }

    }
}
