// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Zuuse.Accounts.Client.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class ClientProjectRequest
    {
        /// <summary>
        /// Initializes a new instance of the ClientProjectRequest class.
        /// </summary>
        public ClientProjectRequest()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the ClientProjectRequest class.
        /// </summary>
        public ClientProjectRequest(string clientProjectName = default(string), string clientShortName = default(string), int? clientId = default(int?), int? projectId = default(int?), int? cADocTypeId = default(int?), string ewsApiLocation = default(string))
        {
            ClientProjectName = clientProjectName;
            ClientShortName = clientShortName;
            ClientId = clientId;
            ProjectId = projectId;
            CADocTypeId = cADocTypeId;
            EwsApiLocation = ewsApiLocation;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ClientProjectName")]
        public string ClientProjectName { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ClientShortName")]
        public string ClientShortName { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ClientId")]
        public int? ClientId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ProjectId")]
        public int? ProjectId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "CADocTypeId")]
        public int? CADocTypeId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "EwsApiLocation")]
        public string EwsApiLocation { get; set; }

    }
}
