// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Zuuse.Accounts.Client.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class EmailTemplateCreateRequest
    {
        /// <summary>
        /// Initializes a new instance of the EmailTemplateCreateRequest class.
        /// </summary>
        public EmailTemplateCreateRequest()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the EmailTemplateCreateRequest class.
        /// </summary>
        public EmailTemplateCreateRequest(int? clientId = default(int?), int? projectId = default(int?), string name = default(string), string body = default(string), string subject = default(string), string fromEmail = default(string))
        {
            ClientId = clientId;
            ProjectId = projectId;
            Name = name;
            Body = body;
            Subject = subject;
            FromEmail = fromEmail;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ClientId")]
        public int? ClientId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ProjectId")]
        public int? ProjectId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Name")]
        public string Name { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Body")]
        public string Body { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Subject")]
        public string Subject { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "FromEmail")]
        public string FromEmail { get; set; }

    }
}
