// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Zuuse.Accounts.Client.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class EmailTemplateRequest
    {
        /// <summary>
        /// Initializes a new instance of the EmailTemplateRequest class.
        /// </summary>
        public EmailTemplateRequest()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the EmailTemplateRequest class.
        /// </summary>
        public EmailTemplateRequest(int? clientId = default(int?), int? projectId = default(int?), string templateName = default(string))
        {
            ClientId = clientId;
            ProjectId = projectId;
            TemplateName = templateName;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ClientId")]
        public int? ClientId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ProjectId")]
        public int? ProjectId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "TemplateName")]
        public string TemplateName { get; set; }

    }
}
