// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Zuuse.Accounts.Client.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class ExternalAccountRegistrationRequest
    {
        /// <summary>
        /// Initializes a new instance of the
        /// ExternalAccountRegistrationRequest class.
        /// </summary>
        public ExternalAccountRegistrationRequest()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the
        /// ExternalAccountRegistrationRequest class.
        /// </summary>
        public ExternalAccountRegistrationRequest(string name = default(string), string email = default(string), string phone = default(string), int? expiryInDays = default(int?), bool? multiUse = default(bool?), int? clientId = default(int?), int? projectId = default(int?), System.Guid? filterGuid = default(System.Guid?))
        {
            Name = name;
            Email = email;
            Phone = phone;
            ExpiryInDays = expiryInDays;
            MultiUse = multiUse;
            ClientId = clientId;
            ProjectId = projectId;
            FilterGuid = filterGuid;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Name")]
        public string Name { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Email")]
        public string Email { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Phone")]
        public string Phone { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ExpiryInDays")]
        public int? ExpiryInDays { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "MultiUse")]
        public bool? MultiUse { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ClientId")]
        public int? ClientId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ProjectId")]
        public int? ProjectId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "FilterGuid")]
        public System.Guid? FilterGuid { get; set; }

    }
}
