// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Zuuse.Accounts.Client.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class PinLoginRequest
    {
        /// <summary>
        /// Initializes a new instance of the PinLoginRequest class.
        /// </summary>
        public PinLoginRequest()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the PinLoginRequest class.
        /// </summary>
        public PinLoginRequest(string pin = default(string))
        {
            Pin = pin;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Pin")]
        public string Pin { get; set; }

    }
}
