// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Zuuse.Accounts.Client.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class ResetPasswordResponse
    {
        /// <summary>
        /// Initializes a new instance of the ResetPasswordResponse class.
        /// </summary>
        public ResetPasswordResponse()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the ResetPasswordResponse class.
        /// </summary>
        public ResetPasswordResponse(string newPassword = default(string))
        {
            NewPassword = newPassword;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "NewPassword")]
        public string NewPassword { get; set; }

    }
}
