// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Zuuse.Accounts.Client.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class RoleCollection
    {
        /// <summary>
        /// Initializes a new instance of the RoleCollection class.
        /// </summary>
        public RoleCollection()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the RoleCollection class.
        /// </summary>
        public RoleCollection(IList<string> builtInRoles = default(IList<string>), IList<string> customRoles = default(IList<string>))
        {
            BuiltInRoles = builtInRoles;
            CustomRoles = customRoles;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "BuiltInRoles")]
        public IList<string> BuiltInRoles { get; private set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "CustomRoles")]
        public IList<string> CustomRoles { get; private set; }

    }
}
